# Optimizer defaults
DEFAULT_BETA1 = 0.9
DEFAULT_BETA2 = 0.99
DEFAULT_OPTIMIZER_EPS = 1e-6
DEFAULT_WEIGHT_DECAY = 0.0
DEFAULT_LORA_DROPOUT = 0.0

# Evaluation defaults
DEFAULT_EVALS_PER_RUN = 10
DEFAULT_EVAL_FRACTION = 0.01

# Checkpoint defaults
DEFAULT_CHECKPOINT_INTERVAL_HOURS = 1
DEFAULT_MAX_CHECKPOINTS = 3

# Misc constants
DEEPSPEED_TIMEOUT_HOURS = 2
DATASET_TOKENIZE_BATCH_SIZE = 10