# Optimizer defaults
DEFAULT_BETA1 = 0.9
DEFAULT_BETA2 = 0.99
DEFAULT_EPS = 1e-6

# Evaluation defaults
DEFAULT_EVALS_PER_RUN = 11
DEFAULT_EVAL_FRACTION = 0.01

# Checkpoint defaults
DEFAULT_CHECKPOINT_INTERVAL_HOURS = 1
DEFAULT_MAX_CHECKPOINTS = 3

# Misc constants
DEEPSPEED_TIMEOUT_HOURS = 6
DATASET_MAP_BATCH_SIZE = 10