# ==============================
# MODEL AND OUTPUT CONFIGURATION
# ==============================

model_dir = '/data2/models/Meta-Llama-3.1-8B'
output_dir = '/data/training_runs/llama3_8b_example'

# ===========================
# TRAINING TYPE CONFIGURATION
# ===========================

# Set to perform full fine-tuning instead of training a LoRA adapter
#full_fine_tune = true

# Set to train a QLoRA (against a 4-bit quantised model) instead of a LoRA (against an unquantised model)
load_in_4bit = true

# ==================
# LORA CONFIGURATION
# ==================

lora_rank = 64
lora_alpha = 64      # (default: 1/sqrt(rank) [ie: "Rank-Stabilized LoRA" value])
lora_dropout = 0.05  # (default: 0.0)

# =================================
# MODULE/LAYER FILTER CONFIGURATION
# =================================

# Train only specific modules (defaults to: 'all linear' modules for LoRA, or all modules for full fine-tuning)
#target_modules = ['q_proj', 'k_proj', 'v_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj']

# Train only specific layers (can be combined with target_modules and used with LoRA or full fine-tuning)
#layers_to_transform = '16:31'

# =======================
# OPTIMIZER CONFIGURATION
# =======================

lr = 5e-5
epochs = 1           # (default: 1)
beta1 = 0.9          # (default: 0.9)
beta2 = 0.99         # (default: 0.99)
eps = 1e-6           # (default: 1e-6)
weight_decay = 0.01  # (default: 0.0)

# ========================
# EVALUATION CONFIGURATION
# ========================

eval_fraction = 0.01 # (default: 0.01)
evals_per_run = 10   # (default: 10)

# ======================
# TRAINING CONFIGURATION
# ======================

sequence_len = 32768

# The number of pipeline parallel stages (NOTE: must evenly divide world_size)
pipeline_stages = 1                   # (default: 1)

# Controls the effective batch size: gradient_accumulation_steps x (world_size / pipeline_stages)
gradient_accumulation_steps = 32      # (default: 1)

# Setting this lower can help to drop fewer examples when trying to make equal-sized batches 
eval_gradient_accumulation_steps = 1  # (default: 1)

# Set for optimised LoRA training with hybrid data+pipeline parallelism:
# - Sends high-volume "per token" hidden states over PCIe/NVLink
# - Sends lower-volume "per step" LoRA gradient reductions over Ethernet/InfiniBand
#use_column_major_topology = true

# ========================
# CHECKPOINT CONFIGURATION
# ========================

checkpoint_interval_hours = 1  # (default: 1)
max_checkpoints = 3            # (default: 3)

# =====================
# DATASET CONFIGURATION
# =====================

[[datasets]]
dataset_path = 'raw_text_data/*.txt'
# sample_weight = 1.0  # Default weight (can be omitted)

[[datasets]]
dataset_path = 'structured_data/*.json'

[[datasets]]
dataset_path = 'noisy_data/*.jsonl'
sample_weight = 0.5

[[datasets]]
dataset_path = 'very_noisy_data/*.parquet'
sample_weight = 0.25

# - Text files are read as raw training data, structured formats (json/jsonl/parquet) use their "text" fields
# - All datasets support optional sample_weight for controlling learning influence
# - The HuggingFace dataset cache will be added below the dataset paths and is shared between nodes